anchor_version = "0.22.0"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
cardinal_generator = "Fr66EvvzsspaWwC2TiuSPg6RDwjypvDgshSucFjtnYEK"

[programs.devnet]
cardinal_generator = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"

[programs.testnet]
cardinal_generator = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"

[programs.localnet]
cardinal_generator = "stkBL96RZkjY5ine4TvPihGqW8UHJfch2cokjAPzV8i"
