anchor_version = "0.22.0"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "localnet"
wallet = "./tests/test-key.json"

[programs.mainnet]
solaana_nft_programs_generator = "genSsTXZaAGH1kRUe74TXzwuernqZhJksHvpXiAxBQT"

[programs.devnet]
solaana_nft_programs_generator = "genSsTXZaAGH1kRUe74TXzwuernqZhJksHvpXiAxBQT"

[programs.testnet]
solaana_nft_programs_generator = "genSsTXZaAGH1kRUe74TXzwuernqZhJksHvpXiAxBQT"

[programs.localnet]
solaana_nft_programs_generator = "genSsTXZaAGH1kRUe74TXzwuernqZhJksHvpXiAxBQT"
