org: jpbogle
app: cardinal
service: cardinal-generators
frameworkVersion: "2 || 3"

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: "20201221"
  http:
    cors: true

custom:
  apiGatewayCaching:
    enabled: true
    ttlInSeconds: 300

package:
  individually: true
  include:
    - ./idls/**
    - ./img-generator/fonts/**
    - ./img-generator/assets/**
  exclude:
    - "./node_modules"
    - "./package-lock.json"
    - "./yarn.lock"

functions:
  img-generator:
    environment:
      FONTCONFIG_FILE: /var/task/fonts/fonts.conf
    handler: img-generator/handler.generate
    timeout: 10
    events:
      - http:
          path: /img/{mintId}
          method: get
  metadata-generator:
    handler: metadata-generator/handler.generate
    timeout: 10
    events:
      - http:
          path: /metadata/{mintId}
          method: get

# custom:
#   domains:
#     main:
#       domainName: nft.cardinal.so
#     dev:
#       domainName: dev-nft.cardinal.so
#   customDomain:
#     domainName: ${self:custom.domains.${opt:stage}.domainName}
#     certificateName: "*.cardinal.so"
#     createRoute53Record: true
#     autoDomain: true

plugins:
  # - serverless-domain-manager
  # - serverless-certificate-creator
  - serverless-api-gateway-caching
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-include-dependencies
